### PR TITLE
3.10.2 changes for master

### PR DESCRIPTION
**Pull request by hannesm**
This embeds the changes of 3.10.2 for master, namely #1218 and #1209. Superseeds #1216.

### CODE REVIEW

**Comment by hannesm** [comment]
The CI faliure shows that some generated main.ml now initialize the random device multiple times (there are multiple random devices) -- this is not good. This needs to be investigated and fixed before merge!

**Comment by TheLortex** [comment]
For information, the random devices involved are:
- in `Mirage_impl_stack.direct_stackv4`: by default it's `rng ~time ~mclock ()`
- in `Mirage_impl_conduit` and the test config: `default_random`

**Comment by hannesm** [comment]
IMHO good to be merged.

**Comment by TheLortex** [comment]
CI-wise, this is looking good. The mirage-skeleton PR https://github.com/mirage/mirage-skeleton/pull/299 fixes the remaining errors.

**Comment by hannesm** [comment]
@TheLortex great. Feel free to merge then. For mirage-skeleton, I used to rebase & force-push the `dev` branch (to have the few commits ahead of master clearly visible, and easily merge them to master one day mirage@master is out).

**Comment by dinosaure** [comment]
Thanks both!

**Pull request merged**
