### PR TITLE
Fix regression in `opam depext` and in truncated opam output

### PR DESCRIPTION
**Pull request by samoht**
```
opam install mirage-types>=2.6.0
```
Seems to sometimes be interpreted as a shell redirection. Fix that by quoting the arguments of `opam install`. Ideally this should be fixed in functoria.

### CODE REVIEW

**Comment by samoht** [comment]
Also it seems that `opam depext` is confused by the `>=` constraints. Bug reported upstream: https://github.com/ocaml/opam-depext/issues/47

**Comment by Drup** [comment]
@samoht I though this kind of constraints where enforced with the conflict field in mirage ?

**Comment by samoht** [comment]
True. I just wanted to be sure :-) as I sometime saw `mirage configure` try to remove the current version of mirage to install an older version of `mirage-types` ..

**Comment by Drup** [comment]
@samoht did that happen since functoria and/or with a proper solver ? I know it used to happen.

**Comment by samoht** [comment]
No I haven't seen it since a long time, so that should be fine.

**Pull request merged**
