### PR TITLE
don't generate a myocamlbuild.ml anymore. was needed for old OCaml 4.0

### PR DESCRIPTION
**Pull request by hannesm**
the `let minor, major = Cmd.ocaml_version ()` swaps `minor` and `major`.  There is additionally a piece of code which checks for >=OCaml-4.02.3... Thus this piece of code is never executed, and can be removed.

### CODE REVIEW

**Comment by Drup** [comment]
I'm always happy about removing unneeded crappy stringly code generation.

**Comment by hannesm** [comment]
anyone (@samoht @avsm @djs55 @mato @talex5 @mor1) has a strong opinion on keeping this string?

**Comment by mor1** [comment]
Seems to be targeted at OCaml versions we no longer support, or wish to support, and isn't this all to be handled by `topkg` now anyway?

Kill it I say :)

**Comment by hannesm** [comment]
@mor1 unfortunately we currently use topkg only for libraries, but the build system "generated" by the mirage cli uses a Makefile and direct `ocamlbuild` invocations.

**Comment by mor1** [comment]
Oh right; but still, if for a version of OCaml we don't care about anymore, is there any reason to keep it?

**Comment by hannesm** [comment]
no. at least IMHO no.

**Comment by avsm** [comment]
This can be removed, the upstream bug was in https://caml.inria.fr/mantis/view.php?id=6059 and included in 4.01.0

Thanks for the cleanup @hannesm !

**Comment by avsm** [comment]
CI is failing with an unrelated solo5 error 

```
#=== ERROR while installing mirage-console-solo5.dev~mirage ===================#
# opam-version         1.2.2 (58ef3b8213100953848d362f7120a30356d7f77d)
# os                   linux
# command              ocaml pkg/pkg.ml build --pinned false
# path                 /home/opam/.opam/4.03.0/build/mirage-console-solo5.dev~mirage
# compiler             4.03.0
# exit-code            1
# env-file             /home/opam/.opam/4.03.0/build/mirage-console-solo5.dev~mirage/mirage-console-solo5-6558-52128c.env
# stdout-file          /home/opam/.opam/4.03.0/build/mirage-console-solo5.dev~mirage/mirage-console-solo5-6558-52128c.out
# stderr-file          /home/opam/.opam/4.03.0/build/mirage-console-solo5.dev~mirage/mirage-console-solo5-6558-52128c.err
### stdout ###
# [...]
# Error: The implementation lib/console_solo5.ml
#        does not match the interface lib/console_solo5.cmi:
#        Values do not match:
#          val read : 'a -> [> `Eof ] Lwt.t
#        is not included in
#          val read :
#            t -> ([ `Data of buffer | `Eof ], V1.Flow.error) Result.result io
#        File "lib/console_solo5.ml", line 45, characters 4-8:
#          Actual declaration
# Command exited with code 2.
### stderr ###
# pkg.ml: [ERROR] cmd ['ocamlbuild' '-use-ocamlfind' '-classic-display' '-tag' 'debug'
#      '-build-dir' '_build' 'opam' 'pkg/META' 'CHANGES.md' 'LICENSE.md'
#      'README.md' 'lib/mirage-console-solo5.a' 'lib/mirage-console-solo5.cmxs'
#      'lib/mirage-console-solo5.cmxa' 'lib/mirage-console-solo5.cma'
#      'lib/console_solo5.cmx' 'lib/console_solo5.cmi' 'lib/console_solo5.mli']: exited with 10
```

**Pull request merged**
