### PR TITLE
cohttp-mirage is released as 1.0.0

### PR DESCRIPTION
**Pull request by hannesm**
and not as 3.0.0.  the most recent mirage (3.0.6) won't work :(

### CODE REVIEW

**Comment by hannesm** [comment]
found via https://travis-ci.org/mirage/mirage-skeleton/jobs/306405459

**Comment by hannesm** [comment]
the alternative would be to release cohttp-mirage as 3.0.0, but I fear that will be rather brittle if the rest of cohttp version numbers is 1.0.0 (and thus releases of cohttp would need some custom magic).

this certainly needs another mirage (3.0.7) release really soon now, since 3.0.6 is broken (in case you try to use the http stuff).

**Comment by hannesm** [comment]
Travis CI is passing, it would be great to get this + a fresh mirage released to unbreak the current universe with mirage + http.  @djs55 @yomimono

**Comment by djs55** [comment]
LGTM!

**Comment by djs55** [comment]
A trivial `CHANGES.md` update is in #871

**Pull request merged**
