### PR TITLE
Prepare to release 3.0.5 again

### PR DESCRIPTION
**Pull request by djs55**
Signed-off-by: David Scott <dave@recoil.org>

### CODE REVIEW

**Comment by yomimono** [comment]
Just went to do this and you beat me to it, thanks!

**Comment by yomimono** [comment]
@djs55, Are you also preparing a tcpip release?

**Comment by avsm** [comment]
should i rebase #855 for this?

**Comment by djs55** [comment]
> On 8 Aug 2017, at 17:13, Mindy Preston <notifications@github.com> wrote:
> 
> @djs55 <https://github.com/djs55>, Are you also preparing a tcpip release?
> 
Yes, I am editing CHANGES.md right now :)

**Comment by djs55** [comment]
@avsm if you've got time, that would be great!

**Comment by djs55** [comment]
I'll merge this and make a release since people are blocked by the current released package set. We can always do another point release with some more improvements soon.

**Comment by avsm** [comment]
Yes I'll test the upper bounds more thoroughly and put it in 3.0.6 instead

**Pull request merged**
