### PR TITLE
Add a --block configure flag for picking ramdisk or file-backed block…

### PR DESCRIPTION
**Pull request by g2p**
… devices

### CODE REVIEW

**Comment by yomimono** [comment]
Fixes #798 .

**Comment by g2p** [comment]
Hold on, my test case was off, the --block=ramdisk case isn't really building a ramdisk yet.

**Comment by yomimono** [comment]
@g2p: try https://github.com/yomimono/mirage/tree/blockier - the method `name` has to be unique among the classes, otherwise there can be strange collisions when Functoria reduces the graph (see https://github.com/mirage/functoria/issues/79).

**Comment by g2p** [comment]
Thank you for digging this up!

I will revise this. There needs to be a way to specify the ramdisk size.

**Comment by g2p** [comment]
I've experimented with `--block-size-sectors` and `--block-sector-size` keys, but in the end, I think the size is best specified programmatically using [`Ramdisk.resize`](https://mirage.github.io/mirage-block-ramdisk/). Having flags that control the size in the ramdisk case and not in the block-file case would be confusing. Command-line flags also can't handle differing sizes for multiple devices.

So, please merge this branch as-is.

**Comment by yomimono** [comment]
@g2p do you not need something like https://github.com/yomimono/mirage/commit/b16848b1c1761a7513b7b10a6ae8da1c971a620f ?  I don't recall the specific surprising behavior we got with this patch or else I'd test myself.

**Comment by g2p** [comment]
@yomimono You're right, I had forgotten your patch when going back on my desktop.
The patch is necessary to pick the right module name in main.ml.
Thank you.

**Pull request merged**
