### PR TITLE
Fix block device naming on Xen when kv_ro_of_fs

### PR DESCRIPTION
**Pull request by samoht**
This should make mirage.io live again. I'm currently testing this, if this works, I'll make a bug-fix 2.6.1 release.

### CODE REVIEW

**Comment by samoht** [comment]
With the last commit https://mirage.io works again. @djs55 I'm not sure to understand the comment that I removed in that commit: why do you need to start numbering the block device from 1 instead of 0?

**Comment by djs55** [comment]
It's useful to reserve disk 0 for the kernel, and start data from 1 since
many systems insist that the kernel is inside a disk (with grub etc). An
alternative is to use partitions but I thought whole extra disks is
probably simpler.

**Comment by samoht** [comment]
But I don't understand how this could work. `mirage.io` seems to map `/dev/loopX` to the 0-th device, not the 1st one.

**Comment by djs55** [comment]
I'm on a phone ATM, so can't browse the code easily, but does Mirage.io use
the generated .xl config file (with new block support in 2.6.0) or does it
have something hardcoded? The generated .xl config file should guarantee
the block device numbers match the mirage generated code

**Comment by samoht** [comment]
Ha I see! it's using a hard-coded value: `"disk = [ '/dev/loopX,,xvda' ]" So should I be using `xvdb` instead? Does the autogen `xl` file should support the fat files? How does it guess which loopback device to use?

**Comment by djs55** [comment]
In the autogen xl file it says something like

Target=path, format=raw, vdev=xvdb

And libxl magically creates a /dev/loop or fires up a tapdisk. A few xen
releases ago this probably didn't work very reliably, but I think it's good
now.

Let me take a look tomorrow (just got back)

**Comment by samoht** [comment]
> In the autogen xl file it says something like

> Target=path, format=raw, vdev=xvdb

> And libxl magically creates a /dev/loop or fires up a tapdisk. A few xen
releases ago this probably didn't work very reliably, but I think it's good
now.

That sounds great!

> Let me take a look tomorrow (just got back)

cool thanks! The related code is https://github.com/mirage/mirage-www-deployment/blob/master/scripts/deploy-tls.sh#L53

**Comment by djs55** [comment]
I think we could always fix this by updating the (global) checked-in .xl
file in the mirage-www-deployment repo but it seems inconsistent to check
in new kernels but keep only one VM config, when there are links between
the two. I think it would be cleaner to always check in the pair of
(kernel, VM config) and customise the VM config at runtime by adjusting
paths etc. I suppose the world would be cleaner if the VM config were
somehow part of the kernel itself, and you could just directly execute the
kernel (a bit like ocamlrun and bytecode)

How about the following plan:

* update the DEPLOY action of travis_mirage.ml to `git commit` the
generated .xl file as well as the kernel. The .xl file has the auto
generated disk configuration where the virtual device (xvda, xvdb) matches
the one compiled-in to the kernel.
* update the prepare-config.sh of mirage-www-deployments to customise only
the specific bits it case about: kernel path, disk path, memory, on_crash,
network instead of rewriting the file from scratch. This way in future we
can change how the VM boots (e.g. switch to booting HVM) without hopefully
having to change the code here too (maybe)

For reference, here's how the .xl files look now:
```
# Generated by Mirage (Sat, 1 Aug 2015 10:43:00 GMT).

name = 'block_test'
kernel = '<path to kernel>'
builder = 'linux'
memory = 256
on_crash = 'preserve'

disk = [ 'format=raw, vdev=xvdb, access=rw, target=<path to disk>' ]

# The network configuration is defined here:
# http://xenbits.xen.org/docs/4.3-testing/misc/xl-network-configuration.html
# An example would look like:
# vif = [ 'mac=c0:ff:ee:c0:ff:ee,bridge=br0' ]
```

What do you think?


On Fri, Jul 31, 2015 at 10:47 PM, Thomas Gazagnaire <
notifications@github.com> wrote:

> In the autogen xl file it says something like
>
> Target=path, format=raw, vdev=xvdb
>
> And libxl magically creates a /dev/loop or fires up a tapdisk. A few xen
> releases ago this probably didn't work very reliably, but I think it's good
> now.
>
> That sounds great!
>
> Let me take a look tomorrow (just got back)
>
> cool thanks! The related code is
> https://github.com/mirage/mirage-www-deployment/blob/master/scripts/deploy-tls.sh#L53
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mirage/mirage/pull/439#issuecomment-126820914>.
>



-- 
Dave Scott

**Comment by talex5** [comment]
> I suppose the world would be cleaner if the VM config were somehow part of the kernel itself, and you could just directly execute the kernel (a bit like ocamlrun and bytecode)

I think these need to be separate: the kernel comes from the VM owner and can be changed by them freely, while the config comes from the sys-admin and defines the resources the kernel is permitted to use. You wouldn't want to let the VM owner control the config.

For tar images, perhaps we should add initrd support instead?

**Comment by djs55** [comment]
Unfortunately the .xl file contains both
- the resources (disks, networks) the kernel is permitted to use
(controlled by the sys-admin I agree)
- configuration tied to the kernel code such as: PV versus HVM; and if HVM
stuff about the virtual hardware need to boot.

It's a shame the file isn't more cleanly separated into an 'internal, only
I should care' section and an 'external stuff I need to access, beware'
part.

I think we can choose between:
1. sysadmin writes their own config file from scratch; this affords maximum
control but it means they need to edit the config files occasionally when
mirage changes (e.g. if we drop PV mode for HVM or if we change the block
device numbering scheme :-)
2. sysadmin bases their config file on the mirage config by some kind of
#include/sed mechanism; this makes it easier to miss a config option (e.g.
if we add a new default that they don't actually want) but avoids the need
to track all our changes.

Unfortunately I think initrds are loaded into RAM, and the goal of using
the tar stuff is to read large datafiles from BLOCK devices directly, to
reduce memory overhead. I'd quite like to make mirage-www-deployments in
future use something other than crunch for all the data, so we can serve
more pictures and pdfs without worry :-)

The BLOCK device numbering change (starting from 1 rather than 0) was
motivated by wanting to support booting from disk images using pygrub and
perhaps real boot loaders in the longer term. It's not tar-specific,
although perhaps I should have made it a separate pull request!

On Sat, Aug 1, 2015 at 12:21 PM, Thomas Leonard <notifications@github.com>
wrote:

> I suppose the world would be cleaner if the VM config were somehow part of
> the kernel itself, and you could just directly execute the kernel (a bit
> like ocamlrun and bytecode)
>
> I think these need to be separate: the kernel comes from the VM owner and
> can be changed by them freely, while the config comes from the sys-admin
> and defines the resources the kernel is permitted to use. You wouldn't want
> to let the VM owner control the config.
>
> For tar images, perhaps we should add initrd support instead?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mirage/mirage/pull/439#issuecomment-126903610>.
>



-- 
Dave Scott

**Comment by samoht** [comment]
I'm happy to close this in favour of #440.

**Comment by djs55** [comment]
OK, when #440 is in I'll try to update the deployment scripts to take advantage of it.

**Comment by samoht** [comment]
Closing as this has been resolved more cleanly by @djs55

**Pull request closed without merging**
