### PR TITLE
Consistent kvro

### LINKED ISSUE #555: mirage configure --kv_ro=crunch configures with mirage-fs-unix on -t unix
```
[fresh] (mirage-dev) user@mirageos:~/mirage-skeleton/kv_ro$ mirage configure -v --kv_ro=crunch
mirage Config file: config.ml
mirage Processing: /home/user/mirage-skeleton/kv_ro/config.ml
mirage => rm -rf /home/user/mirage-skeleton/kv_ro/_build/config.*
mirage =>
  cd /home/user/mirage-skeleton/kv_ro && ocamlbuild -use-ocamlfind -tags annot,bin_annot -pkg mirage config.cmxs
kv_ro
  Name       kv_ro
  Root       /home/user/mirage-skeleton/kv_ro
  Keys       kv_ro=crunch, logs= (default), ocaml_version_check=false, target=unix (default),
    unix=false, warn_error=false (default), xen=false
  
kv_ro Using configuration: /home/user/mirage-skeleton/kv_ro/config.ml
kv_ro Installing OPAM packages.
kv_ro => opam --version
kv_ro opam depext is installed.
kv_ro =>
  opam depext functoria lwt mirage-clock-unix mirage-console mirage-fs-unix mirage-logs mirage-types mirage-types-lwt mirage-unix
# Detecting depexts using flags: x86_64 linux fedora
# The following system packages are needed:
#  - m4
Name        : m4
Version     : 1.4.17
Release     : 6.fc21
Architecture: x86_64
Install Date: Mon 01 Feb 2016 05:37:42 PM GMT
Group       : Applications/Text
Size        : 534915
License     : GPLv3+
Signature   : RSA/SHA256, Sun 17 Aug 2014 05:07:38 PM BST, Key ID 89ad4e8795a43f54
Source RPM  : m4-1.4.17-6.fc21.src.rpm
Build Date  : Sun 17 Aug 2014 05:05:39 PM BST
Build Host  : buildvm-06.phx2.fedoraproject.org
Relocations : (not relocatable)
Packager    : Fedora Project
Vendor      : Fedora Project
URL         : http://www.gnu.org/software/m4/
Summary     : The GNU macro processor
Description :
A GNU implementation of the traditional UNIX macro processor.  M4 is
useful for writing text files which can be logically parsed, and is used
by many programs as part of their build process.  M4 has built-in
functions for including files, running shell commands, doing arithmetic,
etc.  The autoconf program needs m4 for generating configure scripts, but
not for running configure scripts.

Install m4 if you need a macro processor.
# All required OS packages found.
kv_ro =>
  opam install --yes  functoria lwt mirage-clock-unix mirage-console mirage-fs-unix mirage-logs mirage-types mirage-types-lwt mirage-unix
[NOTE] Package functoria is already installed (current version is 1.1.0).
[NOTE] Package lwt is already installed (current version is 2.5.2).
[NOTE] Package mirage-clock-unix is already installed (current version is 1.0.0).
[NOTE] Package mirage-console is already installed (current version is 2.1.3).
[NOTE] Package mirage-fs-unix is already installed (current version is 1.2.0).
[NOTE] Package mirage-logs is already installed (current version is 0.2).
[NOTE] Package mirage-types is already installed (current version is 2.8.0).
[NOTE] Package mirage-types-lwt is already installed (current version is 2.8.0).
[NOTE] Package mirage-unix is already installed (current version is 2.6.0).
kv_ro Generating: main.ml
kv_ro Generating: key_gen.ml
kv_ro =>
  ocamlfind query -format '%p'  -recursive functoria.runtime mirage-clock-unix mirage-console.unix mirage-fs-unix mirage-logs mirage-types.lwt mirage-unix mirage.runtime
kv_ro Configuring for target: unix
[fresh] (mirage-dev) user@mirageos:~/mirage-skeleton/kv_ro$ cat config.ml 
open Mirage

let disk = generic_kv_ro "t"

let main =
  foreign "Unikernel.Main" (console @-> kv_ro @-> kv_ro @-> job)

let () =
  register "kv_ro" [main $ default_console $ disk $ disk]
[fresh] (mirage-dev) user@mirageos:~/mirage-skeleton/kv_ro$ cat main.ml 
(* Generated by kv_ro (Wed, 13 Jul 2016 10:38:02 GMT). *)

open Lwt
let run =
OS.Main.run

let _ = Printexc.record_backtrace true

module Unikernel1 = Unikernel.Main(Console_unix)(Kvro_fs_unix)(Kvro_fs_unix)

module Mirage_logs1 = Mirage_logs.Make(Clock)

let argv_unix1 = lazy (
  OS.Env.argv () >>= (fun x -> Lwt.return (`Ok x))
  )

let console_unix_01 = lazy (
  Console_unix.connect "0"
  )

let direct11 = lazy (
  Kvro_fs_unix.connect "/home/user/mirage-skeleton/kv_ro/t"
  )

let clock1 = lazy (
  return (`Ok ())
  )

let key1 = lazy (
  let __argv_unix1 = Lazy.force argv_unix1 in
  __argv_unix1 >>= function
  | `Error _e -> fail (Failure "argv_unix1")
  | `Ok _argv_unix1 ->
  return (Functoria_runtime.with_argv Key_gen.runtime_keys "kv_ro" _argv_unix1)
  )

let f11 = lazy (
  let __console_unix_01 = Lazy.force console_unix_01 in
  let __direct11 = Lazy.force direct11 in
  let __direct11 = Lazy.force direct11 in
  __console_unix_01 >>= function
  | `Error _e -> fail (Failure "console_unix_01")
  | `Ok _console_unix_01 ->
  __direct11 >>= function
  | `Error _e -> fail (Failure "direct11")
  | `Ok _direct11 ->
  __direct11 >>= function
  | `Error _e -> fail (Failure "direct11")
  | `Ok _direct11 ->
  Unikernel1.start _console_unix_01 _direct11 _direct11
>>= fun t -> Lwt.return (`Ok t)
  )

let mirage_logs1 = lazy (
  let __clock1 = Lazy.force clock1 in
  __clock1 >>= function
  | `Error _e -> fail (Failure "clock1")
  | `Ok _clock1 ->
  let ring_size = None in
  let reporter = Mirage_logs1.create ?ring_size () in
  Mirage_runtime.set_level ~default:Logs.Info (Key_gen.logs ());
  Mirage_logs1.set_reporter reporter;
  Lwt.return (`Ok reporter)
  )

let mirage1 = lazy (
  let __key1 = Lazy.force key1 in
  let __mirage_logs1 = Lazy.force mirage_logs1 in
  let __f11 = Lazy.force f11 in
  __key1 >>= function
  | `Error _e -> fail (Failure "key1")
  | `Ok _key1 ->
  __mirage_logs1 >>= function
  | `Error _e -> fail (Failure "mirage_logs1")
  | `Ok _mirage_logs1 ->
  __f11 >>= function
  | `Error _e -> fail (Failure "f11")
  | `Ok _f11 ->
  Lwt.return_unit
  )

let () =
  let t =
  Lazy.force key1 >>= function
    | `Error _e -> exit 1
    | `Ok _ ->
    Lazy.force mirage_logs1 >>= function
    | `Error _e -> exit 1
    | `Ok _ ->
    Lazy.force mirage1
  in run t
```

Additionally, `mirage configure --help` with a unikernel using `generic_kv_ro` claims that the default is `crunch`, which isn't true (see https://github.com/mirage/mirage/blob/master/lib/mirage.ml#L333 ).

### PR DESCRIPTION
**Pull request by yomimono**
Fixes #555 and #540 .

### CODE REVIEW

**Comment by mor1** [comment]
Haven't tested, but LGTM on inspection :)

**Comment by avsm** [comment]
Yes lgtm, although a small doc patch about this would be handy as I got confused trying to figure out how to get the Unix passthrough working (there is just a mysterious reference to `crunch` in the help, with no mention of the passthrough)

**Comment by Drup** [comment]
Should we add a `direct` option then ? 

My idea was that `direct_kvro` was always the good choice, since it was crunching when needed (xen) and not otherwise (unix). You seem to want consistent crunching (which is probably better indeed), but this mean there is no CLI option for the "smart" one anymore.

**Comment by yomimono** [comment]
Yes, that's a good idea, I'll do that.

**Pull request merged**
