### PR TITLE
remove MacOSX < yosemite support

### PR DESCRIPTION
**Pull request by hannesm**
I don't think anyone is either still using such an arcane system, neither is anyone interested in supporting it.  Or am I wrong here?

### CODE REVIEW

**Comment by hannesm** [comment]
@avsm just to be clear on this: there's no `--unix` flag since MirageOS 3.0 -- these days, it is named `-t unix` :)

**Comment by hannesm** [comment]
the `ci/dockercloud` check asks me to login, I've no clue why it fails (and unlikely I'll ever find out).

**Comment by hannesm** [comment]
errors from travis:

debian-testing + 4.04.2 + xen (same for debian-testing + 4.03.0 + ukvm) -- is there a missing depext @mato?  since when is `asm/msr-index.h` available?  and which package provides is on a `debian-testing` system?
```
#=== ERROR while installing solo5-kernel-ukvm.0.2.2 ===========================#
# opam-version         1.2.2 (58ef3b8213100953848d362f7120a30356d7f77d)
# os                   linux
# command              make ukvm
# path                 /home/opam/.opam/4.04.2/build/solo5-kernel-ukvm.0.2.2
# compiler             4.04.2
# exit-code            2
# env-file             /home/opam/.opam/4.04.2/build/solo5-kernel-ukvm.0.2.2/solo5-kernel-ukvm-18620-ad8886.env
# stdout-file          /home/opam/.opam/4.04.2/build/solo5-kernel-ukvm.0.2.2/solo5-kernel-ukvm-18620-ad8886.out
# stderr-file          /home/opam/.opam/4.04.2/build/solo5-kernel-ukvm.0.2.2/solo5-kernel-ukvm-18620-ad8886.err
### stdout ###
# [...]
# cc -nostdinc -ffreestanding -mno-red-zone -isystem /home/opam/.opam/4.04.2/build/solo5-kernel-ukvm.0.2.2/include-host -std=gnu99 -Wall -Wextra -Werror -O2 -g -I/home/opam/.opam/4.04.2/build/solo5-kernel-ukvm.0.2.2/kernel -c test_hello.c -o test_hello.o
# ld -T /home/opam/.opam/4.04.2/build/solo5-kernel-ukvm.0.2.2/kernel/ukvm/solo5.lds \
# 		 -nostdlib -z max-page-size=0x1000 -static -o test_hello.ukvm /home/opam/.opam/4.04.2/build/solo5-kernel-ukvm.0.2.2/kernel/ukvm/solo5.o test_hello.o 
# mkdir -p _build-ukvm
# cc -Wall -Werror -std=c99 -O2 -g -D__UKVM_HOST__  -c /home/opam/.opam/4.04.2/build/solo5-kernel-ukvm.0.2.2/ukvm/ukvm-core.c -o _build-ukvm/ukvm-core.o
# Makefile.ukvm:23: recipe for target '_build-ukvm/ukvm-core.o' failed
# make[2]: Leaving directory '/home/opam/.opam/4.04.2/build/solo5-kernel-ukvm.0.2.2/tests/test_hello'
# Makefile:36: recipe for target '_test_ukvm_hello' failed
# make[1]: Leaving directory '/home/opam/.opam/4.04.2/build/solo5-kernel-ukvm.0.2.2/tests'
# Makefile:39: recipe for target 'ukvm' failed
### stderr ###
# Makefile.common:28: /home/opam/.opam/4.04.2/build/solo5-kernel-ukvm.0.2.2/Makeconf: No such file or directory
# /home/opam/.opam/4.04.2/build/solo5-kernel-ukvm.0.2.2/ukvm/ukvm-core.c:39:27: fatal error: asm/msr-index.h: No such file or directory
#  #include <asm/msr-index.h>
#                            ^
# compilation terminated.
# make[2]: *** [_build-ukvm/ukvm-core.o] Error 1
# make[1]: *** [_test_ukvm_hello] Error 2
# make: *** [ukvm] Error 2
```

the issue on debian-unstable (looks like errors from a new gcc (the output claims `gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4`) complaining about no fallthrough) - again @mato (since it's in solo5 codebase)

```
#=== ERROR while installing solo5-kernel-virtio.0.2.2 =========================#
# opam-version         1.2.2 (58ef3b8213100953848d362f7120a30356d7f77d)
# os                   linux
# command              make virtio
# path                 /home/opam/.opam/4.03.0/build/solo5-kernel-virtio.0.2.2
# compiler             4.03.0
# exit-code            2
# env-file             /home/opam/.opam/4.03.0/build/solo5-kernel-virtio.0.2.2/solo5-kernel-virtio-27124-48c407.env
# stdout-file          /home/opam/.opam/4.03.0/build/solo5-kernel-virtio.0.2.2/solo5-kernel-virtio-27124-48c407.out
# stderr-file          /home/opam/.opam/4.03.0/build/solo5-kernel-virtio.0.2.2/solo5-kernel-virtio-27124-48c407.err
### stdout ###
# [...]
# cc -nostdinc -ffreestanding -mno-red-zone -isystem /home/opam/.opam/4.03.0/build/solo5-kernel-virtio.0.2.2/include-host -std=gnu99 -Wall -Wextra -Werror -O2 -g -D__SOLO5_KERNEL__ -c virtio/virtio_blk.c -o virtio/virtio_blk.o
# cc -nostdinc -ffreestanding -mno-red-zone -isystem /home/opam/.opam/4.03.0/build/solo5-kernel-virtio.0.2.2/include-host -std=gnu99 -Wall -Wextra -Werror -O2 -g -D__SOLO5_KERNEL__ -c virtio/tscclock.c -o virtio/tscclock.o
# cc -nostdinc -ffreestanding -mno-red-zone -isystem /home/opam/.opam/4.03.0/build/solo5-kernel-virtio.0.2.2/include-host -std=gnu99 -Wall -Wextra -Werror -O2 -g -D__SOLO5_KERNEL__ -c virtio/clock_subr.c -o virtio/clock_subr.o
# cc -nostdinc -ffreestanding -mno-red-zone -isystem /home/opam/.opam/4.03.0/build/solo5-kernel-virtio.0.2.2/include-host -std=gnu99 -Wall -Wextra -Werror -O2 -g -D__SOLO5_KERNEL__ -c abort.c -o abort.o
# cc -nostdinc -ffreestanding -mno-red-zone -isystem /home/opam/.opam/4.03.0/build/solo5-kernel-virtio.0.2.2/include-host -std=gnu99 -Wall -Wextra -Werror -O2 -g -D__SOLO5_KERNEL__ -DASM_FILE -c cpu.S -o cpu.o
# cc -nostdinc -ffreestanding -mno-red-zone -isystem /home/opam/.opam/4.03.0/build/solo5-kernel-virtio.0.2.2/include-host -std=gnu99 -Wall -Wextra -Werror -O2 -g -D__SOLO5_KERNEL__ -DASM_FILE -c cpu_vectors.S -o cpu_vectors.o
# cc -nostdinc -ffreestanding -mno-red-zone -isystem /home/opam/.opam/4.03.0/build/solo5-kernel-virtio.0.2.2/include-host -std=gnu99 -Wall -Wextra -Werror -O2 -g -D__SOLO5_KERNEL__ -c ee_printf.c -o ee_printf.o
# Makefile:70: recipe for target 'ee_printf.o' failed
# make[1]: Leaving directory '/home/opam/.opam/4.03.0/build/solo5-kernel-virtio.0.2.2/kernel'
# Makefile:32: recipe for target 'virtio' failed
### stderr ###
# ee_printf.c:641:9: note: here
# [...]
# ee_printf.c:656:19: error: this statement may fall through [-Werror=implicit-fallthrough=]
#              flags |= UPPERCASE;
#                    ^
# ee_printf.c:658:9: note: here
#          case 'x':
#          ^~~~
# cc1: all warnings being treated as errors
# make[1]: *** [ee_printf.o] Error 1
# make: *** [virtio] Error 2
```

**Comment by avsm** [comment]
You can ignore the Docker Cloud one; I'm going to disable it soon (it used to rebuild the docs, but I am transitioning that to the new OCL build infra)

**Comment by mato** [comment]
> debian-testing + 4.04.2 + xen (same for debian-testing + 4.03.0 + ukvm) -- 
> is there a missing depext @mato?  since when is `asm/msr-index.h` 
> available?  and which package provides is on a `debian-testing` system?

I checked v0.2.2 in git (since on solo5 master this code is all different) 
and it has the requisite depext in solo5-kernel-ukvm.opam, which is 
"linux-libc-dev". So not sure why it's not being installed in the CI 
environment.

> the issue on debian-unstable (looks like errors from a new gcc (the output 
> claims `gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4`) complaining about no 
> fallthrough) - again @mato (since it's in solo5 codebase)

I believe this has been fixed on master, but since we don't do backports 
it'll have to wait until a new solo5-kernel-xxxx release.

**Comment by hannesm** [comment]
thanks for clarification @mato.  I also discovered in https://github.com/ocaml/opam-repository/pull/10350 that the behaviour differs in opam 1 and opam 2 -- where opam 1 fails on debian-testing and debian-unstable, opam 2 works fine (as in installs the right depext and the tests pass).  any idea what the issue is there?

**Comment by mato** [comment]
FWIW this should go green once https://github.com/ocaml/opam-repository/pull/10350 is merged.

**Comment by hannesm** [comment]
as @mato said, travis is green now, and since @avsm approved the changes, I merge this.

**Pull request merged**
