### PR TITLE
Add --no-depext flag

### PR DESCRIPTION
**Pull request by talex5**
This is useful if you don't have root access, since otherwise mirage
tries to run sudo and fails.

Closes: #401

### CODE REVIEW

**Comment by samoht** [comment]
Could you turn on the new option to build a new GCC compiler in Travis: `UPDATE_GCC_BINUTILS=1`

See https://github.com/ocaml/ocaml-travisci-skeleton/pull/39 (which should probably be documented somewhere ... @hannesm?)

**Comment by talex5** [comment]
I've added the flag, but it seems to make no difference.

**Comment by samoht** [comment]
```
export FORK_USER=dsheets
FORK_USER=dsheets
```
it still uses @dsheets fork, I think https://github.com/mirage/mirage/blob/master/.travis.yml#L3 should point to ocaml/master

**Comment by talex5** [comment]
Ah, didn't spot that one! Fixed now.

**Comment by samoht** [comment]
Thanks!

**Pull request merged**
