### PR TITLE
Topkg

### PR DESCRIPTION
**Pull request by samoht**
Switch to topkg. At the same time, simplify the packaging to get ride of the depopts. When now have 3 packages instead of 2 packages (+1 virtual package):

| opam name | new ocamlfind name | old ocamlfind names |
| ---------------- | ------------ | ----- | 
|  mirage | mirage | mirage |
| mirage-types | mirage-types | mirage-types, mirage-types.lwt |
| mirage-types-lwt | mirage-types-lwt | |

So users of `mirage-types.lwt` will have to change to `mirage-types-lwt`.

### CODE REVIEW

**Comment by samoht** [comment]
Also, I've removed the `lib_tests` directory which seemed unused (/cc @Drup who seems to have committed some stuff in there in the last 3 years).

/cc @dbuenzli

**Comment by yomimono** [comment]
The contents of `lib_test` seem to be an outdated mirror of `mirage-skeleton`, and I think I dimly remember a conversation with @drup to this effect -- removing them seems sensible to me.

**Comment by Drup** [comment]
I confirm the remarks about `lib_test` ... I actually though I removed it already.

**Comment by avsm** [comment]
This is a big change due to the ocamlfind naming change, so it needs to go in soon.  I've resolved the merge conflict in #590

**Pull request merged**
