### PR TITLE
Xen pvh via solo5 for master

### PR DESCRIPTION
**Pull request by hannesm**
this syncs the changes on the 3 branch back to master.

### CODE REVIEW

**Comment by hannesm** [comment]
the last commit will result in travis faiing until https://github.com/ocaml/opam-repository/pull/17485 is merged (since opam pin version information is inferred from opam-repository).

**Review by mato — APPROVED** [review]
LGTM. Thanks for doing this!

If you don't mind, could you add a `Co-Authored-By` on the relevant commits?

**Comment by dinosaure** [comment]
Should we merge it now in master?

**Comment by hannesm** [comment]
@mato thanks for the reminder, I added Co-Authored-By comments to the relevant commits, and force-pushed here. Let's wait for CI again, and merge once it is green.

**Pull request merged**
