### PR TITLE
On a `Term error from Cmdliner, print a Hint about how to pass a space

### PR DESCRIPTION
**Pull request by hannesm**
See #1248 @samoht @patricoferris @pitag-ha

Of course, happy to improve the text. But since this is a pretty common issue, I'm happy to have such a hint.

console-hint

### CODE REVIEW

**Comment by hannesm** [comment]
There's another way how to get it working: `--hello='foo\ bar'` (or the mentioned `--hello='"foo bar"'`). I'm undecided which one is easier to understand, and what the leading sentence should be. :)

**Comment by palainp** [comment]
I prefer `'foo\ bar'` but it seems easier to use double quotes in shell scripts, so LGTM :)

**Comment by hannesm** [comment]
@palainp thanks. I updated the docstring. It now includes both options.

console-hint2

**Review by palainp — APPROVED** [review]

**Comment by palainp** [comment]
Thank you !

**Comment by samoht** [comment]
I'm still not very satisfied we need to impose such a dance on the users. But this is a more general issue. This PR is a good change anyway :-) feel free to merge!

**Comment by hannesm** [comment]
And the issue is re-appearing every few years:
- https://github.com/mirage/parse-argv/pull/6
- https://github.com/Solo5/solo5/issues/281
- https://github.com/Solo5/solo5/pull/283
- https://github.com/mirage/mirage-solo5/issues/33
- https://github.com/mirage/mirage-bootvar-unix/pull/2
- https://github.com/mirage/mirage/issues/1248

And my opinion is: let's keep the amount of parsing at a minimum to the C land, and have all of it consistent across targets (otherwise it is really confusing).

**Pull request merged**
