### PR TITLE
ipaddr 5.0.0 compatibility (3.7)

### PR DESCRIPTION
**Pull request by hannesm**

### CODE REVIEW

**Comment by samoht** [comment]
I've pushed https://github.com/mirage/mirage/pull/1175 to try to fix the CI for that branch.

**Comment by samoht** [comment]
And https://github.com/mirage/mirage/pull/1176 forward-port this PR to master.

**Comment by samoht** [comment]
Could you rebase this on the 3.7 branch please? Thanks!

**Comment by samoht** [comment]
```

**Comment by hannesm** [comment]
well, I guess this PR has to wait for charrua, tcpip, tuntap to be released to opam repository.

**Comment by hannesm** [comment]
ok, travis CI has run:
- dhcp-server does not work yet (awaiting https://github.com/ocaml/opam-repository/pull/16688 being merged for ipaddr 5.0 and tcpip 5.0 compatibility)
- on qubes, the ipv4 stack does not work with the changes - see https://github.com/mirage/mirage-qubes/pull/53 which resolves the issue.

since this will be mirage 3.8.0, I pushed a new branch and cut a release from that branch at https://github.com/ocaml/opam-repository/pull/16690

**Pull request closed without merging**
