### PR TITLE
Fix a warning when connecting a ramdisk

### PR DESCRIPTION
**Pull request by g2p**
Follow-up to #800.

### CODE REVIEW

**Comment by hannesm** [comment]
CI failure seems to be related to io-page changes:
```
findlib: [WARNING] Interface io_page.cmi occurs in several directories: /home/opam/.opam/4.03.0/lib/io-page-unix, /home/opam/.opam/4.03.0/lib/io-page
File "_none_", line 1:
Error: Files unikernel.cmx
       and /home/opam/.opam/4.03.0/lib/io-page-unix/io-page-unix.cmxa
       make inconsistent assumptions over interface Io_page
Command exited with code 2.
run ['ocamlbuild' '-use-ocamlfind' '-classic-display' '-tags'
     'predicate(mirage_solo5),warn(A-4-41-42-44),debug,bin_annot,strict_sequence,principal,safe_string'
     '-pkgs'
     'duration,functoria-runtime,io-page,io-page-unix,lwt,mirage-block-solo5,mirage-bootvar-solo5,mirage-clock-freestanding,mirage-logs,mirage-runtime,mirage-solo5,mirage-types,mirage-types-lwt'
     '-cflags' '-g' '-lflags'
     '-g,-dontlink,unix,-dontlink,str,-dontlink,num,-dontlink,threads'
     '-tag-line' '<static*.*>: warn(-32-34)' '-X' '_build-ukvm'
     'main.native.o']: exited with 10
```

**Comment by g2p** [comment]
This is completely trivial, but it's useful to have in the jbuilder era, with dev warnings as errors and more warnings enabled by default.

**Comment by djs55** [comment]
In the latest CI run all are green except the first 3 debian hosts, all of which failed to download some .debs. I think I've seen this happen quite a lot recently. I've hit the rebuild button on those 3 as an experiment but I think there's an issue with the network on travis.

**Comment by g2p** [comment]
See #840 for the apt issue.

**Comment by djs55** [comment]
@g2p ah thanks-- I've filed an issue over on ocaml/ocaml-ci-scripts since this is where the main `.travis-docker.sh` lives which I think pulls custom OCaml + Debian images which will need to be rebuilt.

In the meantime I think it's safe to merge this one!

**Comment by g2p** [comment]
Thanks!

**Pull request merged**
