### PR TITLE
Add an "ldpostflags" variable for Solo5 targets

### PR DESCRIPTION
**Pull request by mato**
Accounts for future flexibity in final link runes for Solo5 targets by
adding an "ldpostflags" pkg-config variable, the contents of which (if
present) are appended to the end of the final link command.

Also fixes a potential bug in the `pkg_config` callout function where
the result should be an empty list if the output is empty.

### CODE REVIEW

**Comment by mato** [comment]
The Travis failures here appear to have something to do with a dependency on `libpcre`, perhaps this needs to be added to the Travis setup explicitly?

**Comment by avsm** [comment]
Pcre should normally be installed via `opam depext` which will find the OS package in the OPAM `conf-pcre` package. Is depext not being called for some reason...

**Comment by mato** [comment]
@avsm I've no idea. There's also a failure building `dns`. Both failures are unrelated to this change. 

Example failures:

Points where it fails:
https://travis-ci.org/mirage/mirage/jobs/193477073#L3443
https://travis-ci.org/mirage/mirage/jobs/193477073#L3619

Stderr:
https://travis-ci.org/mirage/mirage/jobs/193477073#L3634

Failing command:
https://travis-ci.org/mirage/mirage/jobs/193477073#L3735

**Comment by yomimono** [comment]
Merging to get this in before tag; I'm looking at `dns` and a few others today.

**Pull request merged**
