### PR TITLE
call Printexc.record_backtrace early -- will be later overwritten by --backtrace (if provided)

### PR DESCRIPTION
**Pull request by hannesm**
inspired by #1584 //cc @reynir

### CODE REVIEW

**Comment by reynir** [comment]
I think your force push broke the output -- the semi colon is needed I think -- maybe even ;;

**Comment by hannesm** [comment]
Hmm hmm, but with a semicolon it broke as well. Thanks for your comment, I'll figure out what is needed.

**Comment by hannesm** [comment]
see 80693f21

**Comment by reynir** [comment]
I'm afraid this might still call `Printexc.record_backtrace` too late. I have been working on writing a test, but it is very challenging because of opam-monorepo. I may resort to a manual test...

**Comment by hannesm** [comment]
> I'm afraid this might still call `Printexc.record_backtrace` too late. I have been working on writing a test, but it is very challenging because of opam-monorepo. I may resort to a manual test...

Really? I thought calling it at the top of the module as a top-level exprssion will be early enough...

**Comment by reynir** [comment]
My thinking is this:

* A call to `Mirage_runtime.register_arg` in unikernel.ml could be at the top level (if used "incorrectly").
* So the evaluation order depends on what order the modules are linked
* My thinking is main.ml depends on unikernel.ml, so unikernel.ml is linked earlier and thus evaluated earlier.

I am creating a new switch in order to pin mirage[-runtime] to this branch in order to do a manual test. I will report back.

**Comment by hannesm** [comment]
Right, you're absolutely right. So, the place is either your PR or in mirage-runtime at top-level (uncondtionally)!?

**Comment by reynir** [comment]
So indeed:
```
$ ./dist/early-arg 
Fatal error: exception Invalid_argument("Called too early. Please delay this call to after the start function of the unikernel.")
```
(it is annoying I can't figure out how to add this as a cram test /o\)

> So, the place is either your PR or in mirage-runtime at top-level (uncondtionally)!?

Right, I think so. I guess it's maybe fine to do at the top-level unconditionally?? As the unikernel can/will set/unset record_backtrace using the runtime argument. I guess Mirage_runtime is always linked before both unikernel.ml and main.ml.

**Comment by hannesm** [comment]
closing, let's use #1584 -- it should be somewhere in the Mirage_runtime module.

**Pull request closed without merging**
