### PR TITLE
minor nits for pkg.ml

### PR DESCRIPTION
**Pull request by hannesm**

### CODE REVIEW

**Comment by avsm** [comment]
looks like a `mirage-types` specific failure:

```
-> installed mirage-http.dev~mirage
Done.
[ERROR]
  command terminated with exit code 2
stderr: ocamlfind: Package `tls.mirage' not found
```

**Comment by hannesm** [comment]
TLS recently switched to topkg (see https://github.com/mirage/mirage-dev/commit/addf3bf118f04059a88af8f9ca07b57ad85a78cd) (but the conditional when to compile with mirage support did not change -- mirage-types-lwt is still required (ipaddr is a dependency of mirage-types-lwt, and thus should have no effect)) -- mirage-dev builds fine, I cannot reproduce this issue... it only happens here in the mirage repo in the `PACKAGE=mirage-types` cases...

as mentioned yesterday on IRC, the `MODE` in the travis scripts here is also ignored (all runs are build for unix).

If @samoht (and/or others, @avsm) agrees to these nits here, I'd be happy to merge (since I've some more changes based on top this which will be in a separate PR at some point)

**Comment by samoht** [comment]
LGTM

ideally we should remove the conditionals and build V1_LWT only when building `mirage-types-lwt` so I guess it's a step in the right direction.

**Comment by hannesm** [comment]
this will require updates to lots of packages (but may solve the travis issue we currently see) -- atm V1_LWT is distributed as mirage-types.lwt, and mirage-types-lwt is a virtual package (not installing anything).  I put it as an action item onto #670 to not loose the idea.

**Pull request merged**
