### PR TITLE
Misc improvements

### PR DESCRIPTION
**Pull request by Drup**
Something I considered including: making keys (such as dhcp and net) generate an env variable by default. I feel slightly uneasy about this, but it seems to be rather common. What would you prefer ?

### CODE REVIEW

**Comment by Drup** [comment]
@samoht Opinion about having env variables by default ?

**Comment by samoht** [comment]
I think that's good. Not sure if people use it, but that's useful for demos :p

**Comment by Drup** [comment]
For everything ? including IP, all that ?

**Comment by samoht** [comment]
yes I'd say for everything.

**Comment by Drup** [comment]
Note that for demos, it doesn't matter, you can use the command line. It's mostly for scripts ... which should probably move to command line arguments.

**Comment by samoht** [comment]
For demos, I want to be able to tweak some default values without having to add them on the command-line where I can forget to write the right thing. That's not super important though: @avsm what would you prefer/use in general?

**Comment by hannesm** [comment]
I dislike environment variables for this -- although the command line gets shorter and looks more impressive, there's implicit information used, and I rather like it to be explicit.  If you think you forget stuff during a demo, either you get a warning from the unikernel (or you can use shell scripts or aliases to pass information implicitly).  Certainly, this is just my opinion ;)

**Comment by mor1** [comment]
I agree with @hannesm on this -- I'd imagine I'm more likely to forget to set the right env var, or to tweak the right thing than I am to edit a command line where (as @hannesm says) at least everything is right there in front of your face :)

**Comment by samoht** [comment]
ok let's forget about environment variables then :-)

**Pull request merged**
