### PR TITLE
mirage: issues with dune 3.8.0

### PR DESCRIPTION
**Pull request by hannesm**
see  https://github.com/ocaml/dune/issues/7875

### CODE REVIEW

**Comment by hannesm** [comment]
ouch, so with opam-monorepo in the chain we're not able to restrict dune, is it what the CI run is supposed to tell me? https://github.com/tarides/opam-monorepo/issues/378

**Comment by hannesm** [comment]
This also leads me to the question: why is dune in the duniverse? I mean from all I can tell, the dune in the opam switch is used for compilation!? If I downgrade in the opam switch to dune 3.7.1, and then run the opam-monorepo stuff, it locks to dune 3.8.0 in the duniverse, but the compilation succeeds... so, can we remove the dune from the `duniverse`?

**Comment by samoht** [comment]
> why is dune in the universe? 

This is required to by `app-info` (as it uses `build-info`) to add metadata about the libraries linking with the unikernel.

**Comment by hannesm** [comment]
> > why is dune in the universe?
> 
> This is required to by `app-info` (as it uses `build-info`) to add metadata about the libraries linking with the unikernel.

But that `app-info` is optional, no? I have it not enabled anywhere. Since opam-monorepo computes a complete solution (apart from the ocaml compiler?), it's clear that dune is part of that solution (since e.g. mirage-runtime depends on it) -- but if the ocaml compiler is special, shouldn't we put "dune" as well in the special parts (i.e. `x-opam-monorepo-opam-provided` -- but is that field read for computing the dependency cone?)

**Comment by reynir** [comment]
I believe the below issues are relevant. It seems the opam-monorepo lockfile is assumed to be opam install'ed by opam-monorepo, but it is not opam install'ed by mirage.
https://github.com/tarides/opam-monorepo/issues/378
https://github.com/tarides/opam-monorepo/issues/378#issuecomment-1479335882
https://github.com/mirage/mirage/issues/1415

**Comment by samoht** [comment]
I'm not sure I understand your remark. The mirage tool installs the switch dependencies here: https://github.com/mirage/mirage/blob/main/lib/functoria/makefile.ml#L140

Do you mean there's a missing `make switch-depends` missing somewhere?

**Comment by samoht** [comment]
Ha yes good point!!

**Comment by Leonidas-from-XIV** [comment]
Yes, I would say that what @reynir is saying makes sense, it needs to install the dependencies that are not marked as `?vendor` first, since opam-monorepo is not running dune, it is the dune from the environment that is being used.

**Pull request closed without merging**
