### PR TITLE
adapt to logs-syslog change in 0.4: no more console (now using printf)

### PR DESCRIPTION
**Pull request by hannesm**

### CODE REVIEW

**Review by dinosaure — APPROVED** [review]
Errors seems unrelated, one is about lower bounds, the other is about MacOS.

**Comment by hannesm** [comment]
lower bounds issue (there are multiple thereof):
```
File "test/functoria/e2e/describe.t", line 1, characters 0-0:

/usr/bin/git --no-pager diff --no-index --color=always -u _build/.sandbox/c7e920abe4dee985f39a60e1d131af5b/default/test/functoria/e2e/describe.t _build/.sandbox/c7e920abe4dee985f39a60e1d131af5b/default/test/functoria/e2e/describe.t.corrected

diff --git a/_build/.sandbox/c7e920abe4dee985f39a60e1d131af5b/default/test/functoria/e2e/describe.t b/_build/.sandbox/c7e920abe4dee985f39a60e1d131af5b/default/test/functoria/e2e/describe.t.corrected

index 779cc57..fb3c475 100644

--- a/_build/.sandbox/c7e920abe4dee985f39a60e1d131af5b/default/test/functoria/e2e/describe.t

+++ b/_build/.sandbox/c7e920abe4dee985f39a60e1d131af5b/default/test/functoria/e2e/describe.t.corrected

@@ -1,6 +1,10 @@

 Test that `describe` works as expected:

 

   $ ./test.exe describe --file app/config.ml

+  File "/home/opam/.opam/4.10/lib/bigstringaf/bigstringaf.dune", line 1, characters 0-0:

+  Warning: .dune files are ignored since 2.0. Reinstall the library with dune

+  >= 2.0 to get rid of this warning and enable support for the subsystem this

+  library provides.

   Name       noop

   Keys      

     hello=Hello World! (default),
```

with the package set installed:
```
The following actions will be performed:

  - install cmdliner        1.2.0

  - install conf-m4         1

  - install jbuilder        1.0+beta20.1

  - install ocamlbuild      0.14.0

  - install conf-pkg-config 1.0

  - install dune            3.1.0

  - install ocamlfind       1.8.1

  - install bigstringaf     0.2.0

  - install uchar           0.0.2

  - install stdlib-shims    0.1.0

  - install seq             0.2.2

  - install result          1.5

  - install opam-monorepo   0.3.2

  - install mmap            1.0.2

  - install macaddr         5.0.0

  - install topkg           1.0.3

  - install base-bytes      base

  - install angstrom        0.14.0

  - install uutf            1.0.1

  - install rresult         0.7.0

  - install fmt             0.8.10

  - install uuidm           0.9.6

  - install stringext       1.4.0

  - install re              1.7.2

  - install cppo            1.6.1

  - install base64          3.0.0

  - install astring         0.8.2

  - install pecu            0.3

  - install uri             4.2.0

  - install lwt             4.2.0

  - install fpath           0.7.3

  - install domain-name     0.3.0

  - install alcotest        1.0.0

  - install logs            0.6.3

  - install ipaddr          5.0.0

  - install bos             0.2.1

  - install emile           1.1

===== 37 to install =====
```

**Comment by hannesm** [comment]
opam-monorepo compilation issue:
```
#=== ERROR while compiling opam-monorepo.0.3.6 ================================#

# context     2.1.5 | linux/x86_64 | ocaml-variants.5.1.0+trunk | file:///home/opam/opam-repository

# path        ~/.opam/5.1/.opam-switch/build/opam-monorepo.0.3.6

# command     ~/.opam/5.1/bin/dune build -p opam-monorepo -j 31 @install

# exit-code   1

# env-file    ~/.opam/log/opam-monorepo-1-54aa25.env

# output-file ~/.opam/log/opam-monorepo-1-54aa25.out

### output ###

# (cd _build/default && /home/opam/.opam/5.1/bin/ocamlopt.opt -w -40 -w -3 -g -I lib/.duniverse_lib.objs/byte -I lib/.duniverse_lib.objs/native -I /home/opam/.opam/5.1/lib/ocaml/threads -I /home/opam/.opam/5.1/lib/ocaml/unix -I duniverse/0install/src/solver/.zeroinstall_solver.objs/byte -I duniverse/0install/src/solver/.zeroinstall_solver.objs/native -I duniverse/angstrom/lib/.angstrom.objs/byte -I duniverse/angstrom/lib/.angstrom.objs/native -I duniverse/astring/src/.astring.objs/byte -I duniverse/astring/src/.astring.objs/native -I duniverse/base/compiler-stdlib/src/.caml.objs/byte -I duniverse/base/compiler-stdlib/src/.caml.objs/native -I duniverse/base/hash_types/src/.base_internalhash_types.objs/byte -I duniverse/base/hash_types/src/.base_internalhash_types.objs/native -I duniverse/base/shadow-stdlib/src/.shadow_stdlib.objs/byte -I duniverse/base/shadow-stdlib/src/.shadow_stdlib.objs/native -I duniverse/base/src/.base.objs/byte -I duniverse/base/src/.base.objs/native -I duniverse/bigstringaf/lib/.bigstringaf.objs/byte -I duniverse/bigstringaf/lib/.bigstringaf.objs/native -I duniverse/bos/src/.bos.objs/byte -I duniverse/bos/src/.bos.objs/native -I duniverse/cmdliner/src/.cmdliner.objs/byte -I duniverse/cmdliner/src/.cmdliner.objs/native -I duniverse/fmt/src/.fmt.objs/byte -I duniverse/fmt/src/.fmt.objs/native -I duniverse/fpath/src/.fpath.objs/byte -I duniverse/fpath/src/.fpath.objs/native -I duniverse/logs/src/.logs.objs/byte -I duniverse/logs/src/.logs.objs/native -I duniverse/ocaml-re/lib/.re.objs/byte -I duniverse/ocaml-re/lib/.re.objs/native -I duniverse/ocaml-uri/lib/.uri.objs/byte -I duniverse/ocaml-uri/lib/.uri.objs/native -I duniverse/ocaml-version/.ocaml_version.objs/byte -I duniverse/ocaml-version/.ocaml_version.objs/native -I duniverse/ocamlgraph/src/.graph.objs/byte -I duniverse/ocamlgraph/src/.graph.objs/native -I duniverse/opam-0install-solver/lib/.opam_0install.objs/byte -I duniverse/opam-0install-solver/lib/.opam_0install.objs/native -I duniverse/opam-file-format/src/.opam_file_format.objs/byte -I duniverse/opam-file-format/src/.opam_file_format.objs/native -I duniverse/opam/src/core/.opam_core.objs/byte -I duniverse/opam/src/core/.opam_core.objs/native -I duniverse/opam/src/format/.opam_format.objs/byte -I duniverse/opam/src/format/.opam_format.objs/native -I duniverse/opam/src/repository/.opam_repository.objs/byte -I duniverse/opam/src/repository/.opam_repository.objs/native -I duniverse/opam/src/state/.opam_state.objs/byte -I duniverse/opam/src/state/.opam_state.objs/native -I duniverse/parsexp/src/.parsexp.objs/byte -I duniverse/parsexp/src/.parsexp.objs/native -I duniverse/result/.result.objs/byte -I duniverse/result/.result.objs/native -I duniverse/rresult/src/.rresult.objs/byte -I duniverse/rresult/src/.rresult.objs/native -I duniverse/seq/src/.seq.objs/byte -I duniverse/seq/src/.seq.objs/native -I duniverse/sexplib/src/.sexplib.objs/byte -I duniverse/sexplib/src/.sexplib.objs/native -I duniverse/sexplib0/src/.sexplib0.objs/byte -I duniverse/sexplib0/src/.sexplib0.objs/native -I duniverse/stdlib-shims/src/.stdlib_shims.objs/byte -I duniverse/stdlib-shims/src/.stdlib_shims.objs/native -I duniverse/stringext/lib/.stringext.objs/byte -I duniverse/stringext/lib/.stringext.objs/native -I stdext/.stdext.objs/byte -I stdext/.stdext.objs/native -intf-suffix .ml -no-alias-deps -open Duniverse_lib -o lib/.duniverse_lib.objs/native/duniverse_lib__Opam_solve.cmx -c -impl lib/opam_solve.ml)

# File "lib/opam_solve.ml", lines 699-726, characters 4-37:

# 699 | ....calculate :

# 700 |     type context diagnostics.

# 701 |     build_only:bool ->

# 702 |     allow_jbuilder:bool ->

# 703 |     require_cross_compile:bool ->

# ...

# 723 |   in

# 724 |   Solver.calculate ~build_only ~allow_jbuilder ~require_cross_compile

# 725 |     ~preferred_versions ~local_opam_files ~target_packages ~opam_provided

# 726 |     ~pin_depends ?ocaml_version input

# Error: This expression has type

#          build_only:bool ->

#          allow_jbuilder:bool ->

#          require_cross_compile:bool ->

#          preferred_versions:OpamTypes.version OpamPackage.Name.Map.t ->

#          local_opam_files:(OpamTypes.version * OpamFile.OPAM.t)

#                           OpamPackage.Name.Map.t ->

#          target_packages:OpamPackage.Name.Set.t ->

#          opam_provided:OpamPackage.Name.Set.t ->

#          pin_depends:(OpamTypes.version * OpamFile.OPAM.t)

#                      OpamPackage.Name.Map.t ->

#          ?ocaml_version:string ->

#          ('context, 'diagnostics) t ->

#          'context ->

#          (Duniverse_lib.Opam.Dependency_entry.t list,

#           [> `Diagnostics of 'diagnostics | `Msg of string ])

#          result

#        but an expression was expected of type

#          build_only:bool ->

#          allow_jbuilder:bool ->

#          require_cross_compile:bool ->

#          preferred_versions:OpamTypes.version OpamPackage.Name.Map.t ->

#          local_opam_files:(OpamTypes.version * OpamFile.OPAM.t)

#                           OpamPackage.Name.Map.t ->

#          target_packages:OpamPackage.Name.Set.t ->

#          opam_provided:OpamPackage.Name.Set.t ->

#          pin_depends:(OpamTypes.version * OpamFile.OPAM.t)

#                      OpamPackage.Name.Map.t ->

#          ?ocaml_version:string ->

#          ('context, 'diagnostics) t ->

#          'context ->

#          (Duniverse_lib.Opam.Dependency_entry.t list,

#           [> `Diagnostics of 'diagnostics0 | `Msg of string ])

#          result

#        The universal variable 'diagnostics0 would escape its scope
```

with the package set:
```
The following actions will be performed:

  - install cmdliner           1.2.0

  - install dune               3.8.0

  - install ocamlfind          1.9.6

  - install seq                base

  - install ocamlbuild         0.14.2

  - install conf-pkg-config    2

  - install stringext          1.6.0

  - install stdlib-shims       0.3.0

  - install result             1.5

  - install pecu               0.6

  - install ocaml-syntax-shims 1.0.0

  - install macaddr            5.5.0

  - install domain-name        0.4.0

  - install csexp              1.5.2

  - install cppo               1.6.9

  - install base64             3.5.1

  - install base-bytes         base

  - install re                 1.10.4

  - install topkg              1.0.7

  - install opam-monorepo      0.3.6

  - install ipaddr             5.5.0

  - install dune-configurator  3.8.0

  - install ocplib-endian      1.2

  - install uutf               1.0.3

  - install rresult            0.7.0

  - install fmt                0.9.0

  - install astring            0.8.5

  - install bigstringaf        0.9.1

  - install lwt                5.6.1

  - install fpath              0.7.3

  - install alcotest           1.7.0

  - install angstrom           0.15.0

  - install logs               0.7.0

  - install uri                4.2.0

  - install emile              1.1

  - install bos                0.2.1

===== 36 to install =====
```

**Comment by hannesm** [comment]
macOS issue likely addressed in #1425

**Pull request merged**
