### PR TITLE
keys for DNS/HE/GIT devices

### PR DESCRIPTION
**Pull request by hannesm**
works with https://github.com/mirage/mirage-skeleton/pull/403

### CODE REVIEW

**Comment by hannesm** [comment]
To explain the reasoning behind this: some devices have optional arguments -- let's take happy-eyeballs as example, where you can configure the timeout for establishing a connection.

Previously, our interface allowed some unikernel developer to optionally pass a key (of type int64 option) for that -- meaning they could decide whether the resulting unikernel should have `--he-connect-timeout` or not.

Now, we generate this key always -- so all unikernels using happy eyeballs will be configurable, automaticatlly \o/. In addition, if you have two network stacks and a happy eyeballs device on each, you'll be able to have two sets of keys -- `--service-connect-timeout` and `--management-connect-timeout`.

In the end, unikernels are more predictable and developers need to do less. They can still provide their own custom value for the connect_timeout (via the optional argument), but don't need to build keys for doing so. Below the line, our unikernels using git no longer need to expose all the different arguments (ssh_key/ssh_password/ssh_authenticator/http_authenticator/http_headers).

This PR adds some code to mirage, and I'm sure one day we'll be able to condense the code again. But for the time being, the runtime arguments used by mirage devices are declared in that way - and are only of basic types (to limit the dependency cone of mirage-runtime).

Reviews welcome. I'm aware this needs some adjustments in mirage-skeleton that I'll work on soon.

**Comment by hannesm** [comment]
So, CI is happy. Feedback would be highly welcome :)

**Comment by reynir** [comment]
I like the motivation behind this. I briefly looked over the code, but not in depth. I think this is nice.

**Comment by dinosaure** [comment]
Seems good to me, I never used `group` argument but the rational behind seems correct as you described :+1:. I don't have too much time to look on it however.

**Comment by hannesm** [comment]
> Seems good to me, I never used `group` argument but the rational behind seems correct as you described 👍. I don't have too much time to look on it however.

To get a better understanding, the `group` is nice and useful for e.g. network stacks -- considering we have two (in a VPN unikernel, or when doing monitoring) -- here we have the arguments `--ipv4=` and `--management-ipv4=` -- where the first doesn't use `group`, the second `group:"management"`.

**Pull request merged**
