### PR TITLE
generate .xl, .xl.in, .xe, and _libvirt.xml only if we're targeting xen

### PR DESCRIPTION
**Pull request by hannesm**
no use for those when using solo5 afaik

### CODE REVIEW

**Comment by yomimono** [comment]
Isn't `_libvirt.xml` still potentially useful in a non-Xen context?

**Comment by hannesm** [comment]
I've no clue... from mirage.ml:

```
  append fmt "        <type arch='armv7l' machine='xenpv'>linux</type>";
  append fmt "        <kernel>%s/mir-%s.xen</kernel>" root name;
  ...
  append fmt"         <disk type='block' device='disk'>";
  append fmt "            <driver name='phy'/>";
  append fmt "            <source dev='/dev/loop0'/>";
  append fmt "            <target dev='' bus='xen'/>";
  append fmt "        </disk>";

```

If they would be more general, they might be useful with other backends.  I've no clue who (added and who) uses libvirt support (neither do I know or want to know how to fix it for other backends).

**Comment by yomimono** [comment]
I think it was added by @magnuss for Jitsu.  That block is indeed pretty incorrect for non-Xen targets, so I'm fine with this PR; better to have nothing generated than something broken.

**Comment by djs55** [comment]
IIRC it's not possible to write a generic libvirt xml config file-- the
format is more like the union of all formats with an XML syntax. The KVM
device info always looks different to the xen info :(

**Pull request merged**
