### PR TITLE
allow mirage-qubes 0.11 series

### PR DESCRIPTION
**Pull request by hannesm**
for https://github.com/ocaml/opam-repository/pull/26350

### CODE REVIEW

**Comment by palainp** [comment]
Thank you @hannesm I missed that mirage needs that. I would have done better to set 0.10.1 :(
So LGTM!

**Comment by hannesm** [comment]
hmm, it is a bit inconvenient... maybe we should bump to a 1.0 and apply semantic versioning (and then say in mirage to use >= 1 & < 2) -- and then we'll have the freedom and convenience of what everyone thinks about versioning :)

**Comment by hannesm** [comment]
and at the same time, I think our qubes unikernels don't use the target qubes -> so we actually don't need to worry much ;)

the remaining question is whether the qubes target is worth to have and keep, if all our qubes unikernels don't use it (since we need to control tightly the network configuration etc.).

**Comment by palainp** [comment]
I would prefer to keep it for unikernels that don't need downstream links (like a dns-resolver I have) :)

**Pull request merged**
