### PR TITLE
[merge to break everything] types/V1 -> types/mirage_types, types/V1_LWT -> types/mirage_types_lwt

### PR DESCRIPTION
**Pull request by yomimono**
This will break [literally](https://chrome.google.com/webstore/detail/literally/) everything :) I'm automating the process of submitting PRs to the repositories in mirage-dev today and will include links to PRs and a consistent universe here when they're ready.

### CODE REVIEW

**Comment by samoht** [comment]
It won't hopefully break everything, as after all the work we did for splitting `V1` a large number of libs doesn't depend on mirage-types anymore :-)

**Comment by hannesm** [comment]
bla

**Comment by hannesm** [comment]
break all the things

**Comment by yomimono** [comment]
Survey of what will break + methodology:

```
$ #get a local copy of packages in mirage-dev; check out the branch that mirage-dev references
$ for package in `ls -1 ${HOME}/mirage-dev/packages`; do cd ${HOME}/sandbox/$package && git fetch origin && git checkout origin/$(dev-branch $package); done
$ #who references V1 or V1_LWT in something relevant-looking?
$ find . -name *.ml*|xargs grep -lE '(V1\.|V1_LWT\.)'|cut -d/ -f2|sort|uniq
arp
charrua-client
conduit
datakit
datakit-ci
dns
git
git-http
git-mirage
hvsock
irmin
irmin-mirage
logs-syslog
mirage
mirage-block-ccm
mirage-bootvar-xen
mirage-conduit
mirage-dns
mirage-entropy
mirage-net-xen
mirage-qubes
mirage-runtime
mirage-stdlib-random
mirage-types
mirage-types-lwt
mirage-vnetif
mirage-www
nbd
qcow-format
shared-block-ring
tar-format
tcpip
tls
vhd-format
```

**Comment by yomimono** [comment]
Extant PRs:

[ ] - https://github.com/hannesm/arp/pull/3
[ ] - https://github.com/mirage/ocaml-crunch/pull/33
[ ] - https://github.com/docker/datakit/pull/433
[ ] - https://github.com/mirage/ocaml-dns/pull/122
[ ] - https://github.com/mirage/ocaml-fat/pull/62
[ ] - https://github.com/sg2342/mirage-block-ccm/pull/20
[ ] - https://github.com/mirage/mirage-bootvar-xen/pull/30
[ ] - https://github.com/mirage/mirage-entropy/pull/33
[ ] - https://github.com/mirage/mirage-flow/pull/29
[ ] - https://github.com/mirage/mirage-fs-unix/pull/35
[ ] - https://github.com/mirage/mirage-net-xen/pull/56
[ ] - https://github.com/hannesm/mirage-stdlib-random/pull/2
[ ] - https://github.com/magnuss/mirage-vnetif/pull/13
[ ] - https://github.com/mirage/shared-block-ring/pull/51
[ ] - https://github.com/mirage/ocaml-tar/pull/39
[ ] - https://github.com/mirage/ocaml-vhd/pull/44

**Pull request merged**
